INSERT INTO breakdown_db.ideas (title, description, rating) VALUES 
('Community organizing - census', 'apis that gov / un has, connect ppl w/ resources in area. homelessness areas, linked with mapping to shelters. Statistics to resources.',3)
,('Word wars','typing practice game',3)
,('Game vault','digital board game shelf. Coordinate from internet games. Ratings.',3)
,('On-time trains','Crowdsource when trains are late. Helpful in NY. GMaps is not good but ppl can be.',3)
,('Billing - tracking','billing of clients, invoices, expenses. Have they been paid?!?',3)
,('YouTube learning','educational that includes closed captioning.',2)
,('inventory website for small business', 'good for - restaurants, reimagining, esp. for freelancers',4)
,('Spotify + sentiment analysis','based on song words, playlist for mood. MAYBE a facial API to get it. Choosing manually',3)
,('TINDER for pet adoption','Linking animals with adopters',2)
,('LINKEDIN for programmers','maybe by coding boot camps',4)
,('CMS for teachers','when teachers could generate websites for that day. Teacher submits a form, it creates a live website from the form. Chance Eakin - on his github. Two years ago',3)
,('hangman','Word Guess Game',2)
,('trivia','like Jeopardy or more',2)
,('to-do list','Keep / Evernote on programmer steroids',2)
,('grillber','(uber for grills)',4)
,('fitness(running) tracker', 'with specialized features',3)
,('hiking map','courses',3)
,('twitter heat map','by trending words or activities',3)
,('reddit bot','',4)
,('personal finance tracker','budgets and more',3)
,('sms reminder','using api like twilio or nexmo',4)
,('online rpg','self-explanatory',5)
,('gas price map app','',2)
,('random quote machine','',1)
,('markdown previewer','',4)
,('drum machine','',2)
,('pomodoro clock','',2)
,('javascript calculator','',2)
,('full stack comic book archive/museum','',2)
,('jeopardy','',3)
,('connect 4','',3)
,('blackjack','',2)
,('traffic track','',2)
,('countdown clock/alarm clock','',1)
,('tip calculator','',1)
,('house/car payment calculator','',2)
,('spam classifier','',3)
,('rock paper scissors game','',3)
,('text to speech api','',3)
,('bring your umbrella to work notifier','',2)
,('diet/calorie tracking app','',3)
,('meme generator','',3)
,('A GITHUB API CLIENT','(List the popular repositories from today / week / month, and/or List the latest commits in a repository',2)
,('tic tac toe','',2)
,('blog','',2)
,('url shortener','',2)
,('roman numeral to integer converter','',2)
,('trello clone','',5)
,('ip address country locator','',2)
,('zip code look up','',2)
,('Gambling website','odds, bets, results',4)
,('Drone control','Using Bluetooth API and MERN stack',5)
,('Power distribution setup','For movies, outdoor events, e.g.',3)
,('Vote runoff system','Allowing a group to vote on many options',4)
,('Roadtrip Spotify','Where are you going? What is your mood? Make a great playlist for it',2)
,('SpaceHub','All things up in the sky, what''s happening when and what will the weather allow us see?',3)
,('Optimal Seller','See what items sell for online',2)
,('Booze Hub','Find cool bars in my area',3)
,('Whether Weather','Find if the weather will ',3)
,('Medical tracking','Provider OR patient side',3)
,('Bitcoin','Where are bitcoin ATMs!?!',2)
,('Who''s your representative','Government servant finder',2)
,('Recipe generator','Find meals based on current ingredients',2)
,('Career suggester','Based on preferences, etc.',2)
,('departure email template', 'retirement, vacation, suicide, etc.',3)
,('cat battles','https://medium.freecodecamp.org/6-absurd-ideas-for-building-your-first-web-application-24afca35e519#b27b',4)
,('Food Points','Tracked acrossed',3)